drop table if exists TIREUR_DANS_COMPETITIONS;
drop table if exists TIREUR_EQUIPE;
drop table if exists ORGANISATEURCOMPETITION;
drop table if exists TIREUR_DANS_CLUB;
drop table if exists TIREUR_DANS_POULE;
drop table if exists ARBITRE_DANS_COMPETITIONS;
drop table if exists ARBITRE_POULE;
drop table if exists ARBITRE_ELIMINATION;
drop table if exists MATCH_EQUIPE
drop table if exists MATCHPOULE;
drop table if exists POULE;
drop table if exists MATCHELIMINATION; 
drop table if exists ORGANISATEURDANSCLUB;
drop table if exists ARBITRE;
drop table if exists TIREUR;
drop table if exists ORGANISATEUR;
drop table if exists CLUB;
drop table if exists COMPETITION;
drop table if exists EQUIPE;
drop table if exists ARME;
drop table if exists SEXE;
drop table if exists CATEGORIE;
drop table if exists LIEU;

